### ISSUE TITLE
ORC might not be working

### ISSUE THREAD

**Issue by aletc1** [snowlift/trino-storage#155]
Hi,

ORC reader might not be working (Trino 406). TSV/CSV works as expected.

```sql
SELECT * FROM
storage.orc."https://raw.githubusercontent.com/snowlift/trino-storage/master/src/test/resources/example-data/apache-lz4.orc";
```

```
2023-01-30T20:15:24.593Z	ERROR	Query-20230130_201524_00000_hnezj-162	org.ebyhr.trino.storage.StorageClient	Failed to get table: orc.https://raw.githubusercontent.com/snowlift/trino-storage/master/src/test/resources/example-data/apache-lz4.orc
java.lang.RuntimeException: java.io.FileNotFoundException: /tmp/trino-storage-6308204577453222815.orc (No such file or directory)
	at org.ebyhr.trino.storage.operator.OrcPlugin.getReader(OrcPlugin.java:119)
	at org.ebyhr.trino.storage.operator.OrcPlugin.getFields(OrcPlugin.java:55)
	at org.ebyhr.trino.storage.StorageClient.getTable(StorageClient.java:73)
	at org.ebyhr.trino.storage.StorageMetadata.getTableHandle(StorageMetadata.java:71)
	at org.ebyhr.trino.storage.StorageMetadata.getTableHandle(StorageMetadata.java:39)
	at io.trino.spi.connector.ConnectorMetadata.getTableHandle(ConnectorMetadata.java:121)
	at io.trino.metadata.MetadataManager.lambda$getTableHandle$4(MetadataManager.java:281)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:275)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1516)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1508)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:5360)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2149)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:476)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4416)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2878)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:476)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1449)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:476)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:455)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:267)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:204)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:856)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:143)
	at io.trino.$gen.Trino_406____20230130_201510_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.FileNotFoundException: /tmp/trino-storage-6308204577453222815.orc (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at io.trino.orc.FileOrcDataSource.<init>(FileOrcDataSource.java:30)
	at org.ebyhr.trino.storage.operator.OrcPlugin.getReader(OrcPlugin.java:116)
	... 42 more
```

**Comment by nineinchnick** [comment]
I'm not sure it's safe to use a version built for 405 with 406. I'll try to do a new release.

**Comment by aletc1** [comment]
> I'm not sure it's safe to use a version built for 405 with 406. I'll try to do a new release.

Also doesnt work in 405, tested already ;)

**Comment by nineinchnick** [comment]
I was able to reproduce it. It looks like it doesn't work with `https`, local files can be read.

**Comment by aletc1** [comment]
> I was able to reproduce it. It looks like it doesn't work with `https`, local files can be read.

I have a fix. I could do a push request if you like.

**Comment by nineinchnick** [comment]
Please do! I've spotted the issue too but would be very nice to have more contributors in this repo :-)

**Comment by aletc1** [comment]
> Please do! I've spotted the issue too but would be very nice to have more contributors in this repo :-)

Here you have it #157

BTW this is a very nice project. Reading a file directly without Hive is awesome.
