### ISSUE TITLE
Getting method not found error

### ISSUE THREAD

**Issue by siripurapugopi** [snowlift/trino-storage#167]
After copying all the generated jar into trino-server/plugin/storage, getting below error while starting the trino.

2023-04-10T13:24:21.163Z        INFO    main    io.trino.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/storage.properties --
2023-04-10T13:24:22.356Z        ERROR   main    io.trino.server.Server  'int io.airlift.slice.SizeOf.instanceSize(java.lang.Class)'
java.lang.NoSuchMethodError: 'int io.airlift.slice.SizeOf.instanceSize(java.lang.Class)'
        at io.airlift.stats.TDigest.<clinit>(TDigest.java:44)
        at io.airlift.stats.DecayTDigest.<init>(DecayTDigest.java:43)
        at io.airlift.stats.TimeDistribution.<init>(TimeDistribution.java:56)
        at io.airlift.stats.TimeStat.<init>(TimeStat.java:58)
        at io.airlift.stats.TimeStat.<init>(TimeStat.java:52)
        at io.trino.plugin.hive.aws.AwsSdkClientCoreStats.<init>(AwsSdkClientCoreStats.java:49)
        at io.trino.plugin.hive.s3.TrinoS3FileSystemStats.<init>(TrinoS3FileSystemStats.java:50)
        at io.trino.plugin.hive.s3.TrinoS3FileSystem.<clinit>(TrinoS3FileSystem.java:235)
        at io.trino.plugin.hive.s3.HiveS3Module.setup(HiveS3Module.java:50)
        at io.airlift.configuration.AbstractConfigurationAwareModule.configure(AbstractConfigurationAwareModule.java:46)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
        at com.google.inject.spi.Elements.getElements(Elements.java:108)
        at com.google.inject.spi.Elements.getElements(Elements.java:101)
        at io.airlift.configuration.ConfigurationFactory.registerConfigurationClasses(ConfigurationFactory.java:179)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:218)
        at org.ebyhr.trino.storage.StorageConnectorFactory.create(StorageConnectorFactory.java:60)
        at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:410)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:257)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:246)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:232)
        at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
        at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at io.trino.server.Server.doStart(Server.java:129)
        at io.trino.server.Server.lambda$start$0(Server.java:81)
        at io.trino.$gen.Trino_385____20230410_132404_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:81)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)

2023-04-10T13:24:22.357Z        INFO    Thread-73       io.airlift.bootstrap.LifeCycleManager   JVM is shutting down, cleaning up
2023-04-10T13:24:22.357Z        INFO    Thread-73       io.airlift.bootstrap.LifeCycleManager   Life cycle stopping...

**Java version:**

openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)

**Comment by ebyhr** [comment]
Please use the new Trino version.
