### ISSUE TITLE
Trino 420 startup error (with trino-storage v417)

### ISSUE THREAD

**Issue by metalshanked** [snowlift/trino-storage#191]
Hi,

Seem to be getting the below error which crashes Trino (v420) on startup with this trino-storage connector (v417)
Note: Worked fine on  Trino server < 419

```
2023-06-22T18:50:00.303171993-05:00 2023-06-22T23:50:00.302Z	ERROR	main	io.trino.server.Server	io/trino/spi/ptf/ConnectorTableFunction
java.lang.NoClassDefFoundError: io/trino/spi/ptf/ConnectorTableFunction
2023-06-22T18:50:00.303187092-05:00 	at org.ebyhr.trino.storage.StorageModule.configure(StorageModule.java:64)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
2023-06-22T18:50:00.303194245-05:00 	at com.google.inject.spi.Elements.getElements(Elements.java:108)
2023-06-22T18:50:00.303196039-05:00 	at com.google.inject.spi.Elements.getElements(Elements.java:101)
2023-06-22T18:50:00.303197952-05:00 	at io.airlift.configuration.ConfigurationFactory.registerConfigurationClasses(ConfigurationFactory.java:179)
2023-06-22T18:50:00.303199475-05:00 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:216)
2023-06-22T18:50:00.303201288-05:00 	at org.ebyhr.trino.storage.StorageConnectorFactory.create(StorageConnectorFactory.java:60)
	at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:221)
2023-06-22T18:50:00.303204705-05:00 	at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:130)
2023-06-22T18:50:00.303206218-05:00 	at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
2023-06-22T18:50:00.303207771-05:00 	at io.trino.connector.StaticCatalogManager.lambda$loadInitialCatalogs$1(StaticCatalogManager.java:158)
2023-06-22T18:50:00.303209364-05:00 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-06-22T18:50:00.303210866-05:00 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-06-22T18:50:00.303212500-05:00 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-06-22T18:50:00.303214163-05:00 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
2023-06-22T18:50:00.303215786-05:00 	at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
	at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
2023-06-22T18:50:00.303219002-05:00 	at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:152)
2023-06-22T18:50:00.303220825-05:00 	at io.trino.server.Server.doStart(Server.java:144)
2023-06-22T18:50:00.303222368-05:00 	at io.trino.server.Server.lambda$start$0(Server.java:91)
	at io.trino.$gen.Trino_420____20230622_234944_1.run(Unknown Source)
2023-06-22T18:50:00.303225975-05:00 	at io.trino.server.Server.start(Server.java:91)
2023-06-22T18:50:00.303227598-05:00 	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
2023-06-22T18:50:00.303229171-05:00 Caused by: java.lang.ClassNotFoundException: io.trino.spi.ptf.ConnectorTableFunction
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2023-06-22T18:50:00.303232267-05:00 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2023-06-22T18:50:00.303233780-05:00 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2023-06-22T18:50:00.303235353-05:00 	at io.trino.server.PluginClassLoader.loadClass(PluginClassLoader.java:124)
2023-06-22T18:50:00.303236916-05:00 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2023-06-22T18:50:00.303238488-05:00 	... 23 more
2023-06-22T18:50:00.303239921-05:00 
2023-06-22T18:50:00.303241354-05:00 
2023-06-22T18:50:00.304108025-05:00 2023-06-22T23:50:00.303Z	INFO	Thread-107	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
2023-06-22T23:50:00.304Z	INFO	Thread-104	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
2023-06-22T18:50:00.304601834-05:00 2023-06-22T23:50:00.304Z	INFO	Thread-100	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
2023-06-22T18:50:00.304613827-05:00 2023-06-22T23:50:00.304Z	INFO	Thread-107	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
```

**Comment by ebyhr** [comment]
The version should be same between Trino server and this plugin. Please rebuild by yourself until we release the next version.

**Comment by metalshanked** [comment]
Thanks. Unfortunately, that means the trino-storage build will always be behind trino server so I have to manually build for each trino release.
