### ISSUE TITLE
Missing details about Catalog properties file

### ISSUE THREAD

**Issue by almiodescartes** [snowlift/trino-storage#87]
The contributors have done an excellent work  in creating this connector. To use it I would appreciate if you could please mention details about the properties to be added to trino-storage catalog properties file. 
Connector name?
Connection url?
Any other properties.

**Comment by almiodescartes** [comment]
Used connector.name=storage and tried running trino server. Got below error:

```
2022-05-02T09:51:41.728+0530	INFO	main	io.trino.metadata.StaticCatalogStore	-- Loading catalog etc/catalog/storage.properties --
2022-05-02T09:51:41.728+0530	ERROR	main	io.trino.server.Server	io/airlift/bootstrap/Bootstrap
java.lang.NoClassDefFoundError: io/airlift/bootstrap/Bootstrap
	at org.ebyhr.trino.storage.StorageConnectorFactory.create(StorageConnectorFactory.java:48)
	at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:403)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:252)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:241)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:227)
	at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.trino.server.Server.doStart(Server.java:128)
	at io.trino.server.Server.lambda$start$0(Server.java:80)
	at io.trino.$gen.Trino_376____20220502_042132_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:80)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.lang.ClassNotFoundException: io.airlift.bootstrap.Bootstrap
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at io.trino.server.PluginClassLoader.loadClass(PluginClassLoader.java:113)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 12 more

```

**Comment by Piyushency** [comment]
Finally figured it out:
Steps:
1. Create a directory in trino-server/plugin and name it storage.
2. Build trino-storage connector as mentioned in Readme
3. Unzip all the files from trino-storage/target/trino-storage-380.zip and copy all the jar files to trino-server/plugin/storage.
4. Now run the trino server

**Comment by Piyushency** [comment]
Finally figured it out:
Steps:

Create a directory in trino-server/plugin and name it storage.
Build trino-storage connector as mentioned in Readme
Unzip all the files from trino-storage/target/trino-storage-380.zip and copy all the jar files to trino-server/plugin/storage.
Now run the trino server

**Comment by Piyushency** [comment]
Follow these steps

1.Create a directory in trino-server/plugin and name it storage.
2. Build trino-storage connector as mentioned in Readme
3. Unzip all the files from trino-storage/target/trino-storage-380.zip and copy all the jar files to trino-server/plugin/storage.
4. Create a storage.properties file in trino-server/etc/catalog and write `connector.name=storage` as property
Now run the trino server
